# Generated by Django 3.2.6 on 2022-02-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imgid', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
    ]
